[tool.poetry]
name = "myweather"
version = "0.2.0"
description = "An openweathermap wrapper"
authors = ["tct123 <42028373+tct123@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
#...
urls = {"Website" = "https://github.com/tct123/MyWeather"}
